services:
  llm-api-test:
    image: llm-api-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-api-test
    #ports:
    #-"8080:80"
    restart: unless-stopped
